# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts-home
helmCharts:
- name: sample-app
  releaseName: sample-app
  namespace: dev
  version: 0.1.0
  valuesFile: values.yaml

# patches:
# - path: patches/node_affinity_deployment.yaml
#   target:
#     kind: Deployment
